class SharedPrefKeys {
  SharedPrefKeys._();
  static const String languageCode = 'languageCode';
  static const String ServerAddress= 'ServerAddress';
  static const String DbName = 'DbName';
  static const String DbUName = 'DbUName';
  static const String DbUPass = 'DbUPass';
  static const String ApiPrefix = 'ApiPrefix';
  static const String AppLanguage = 'AppLanguage';
  static const String ResPriceGroupId = 'ResPriceGroupId';
  static const String ResourcesGridType = 'ResourcesGridType';
  static const String GridCrossAxisCnt = 'GridCrossAxisCnt';
  static const String phoneNumber = 'phoneNumber';
  static const String address = 'address';
  static const String gridOrList = 'gridOrList';
  static const String twoOrThree = 'twoOrThree';
  static const String baseUrl = 'baseUrl';
  static const String salesman = 'salesman';
  static const String defaultUrl = '192.168.1.200:1433';
  static const String defaultServerPort = '1433';
  static const String defaultDbUName = 'sa';
  static const String defaultDbName = 'akhasap_db';
  static const String printerUrl = '192.168.1.123';
  static const String cashUrl = '192.168.1.124';
  static const String printerList = 'printerList';
  static const String defaultPrinter = 'defaultPrinter';
  static const String cashPrinter = 'cashPrinter';
  static const String selectedPrintType='selectedPrintType';
  static const String selectedDbConnectionType='selectedDbConnectionType';
  static const String socketAddress='socketAddress';
}
